server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false